"""initial migration

Revision ID: 6ee218c9b1e4
Revises: 51f5ccfba190
Create Date: 2016-10-30 23:13:54.444000

"""

# revision identifiers, used by Alembic.
revision = '6ee218c9b1e4'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorys_name'), 'categorys', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categorys_name'), table_name='categorys')
    op.drop_table('categorys')
    ### end Alembic commands ###
